"""Create tables

Revision ID: 2224f925ec0c
Revises: 9e4fcc7dc9dc
Create Date: 2024-09-03 15:38:32.911416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2224f925ec0c'
down_revision = '9e4fcc7dc9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dolls', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('accessories', sa.String(), nullable=True))
        batch_op.drop_column('reliable')
        batch_op.drop_column('most')
        batch_op.drop_column('cheapest')

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.drop_column('siblings')
        batch_op.drop_column('episodes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episodes', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('siblings', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cheapest', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('most', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('reliable', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('accessories')
        batch_op.drop_column('dolls')

    # ### end Alembic commands ###
