"""Create tables

Revision ID: 8382e4a65c52
Revises: b18606fd8634
Create Date: 2024-09-10 16:37:48.788292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8382e4a65c52'
down_revision = 'b18606fd8634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('friends', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('enemies', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.drop_column('enemies')
        batch_op.drop_column('friends')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
