"""empty message

Revision ID: ad924b8347bc
Revises: 
Create Date: 2024-09-24 19:04:54.547875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad924b8347bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('parents', sa.String(), nullable=True),
    sa.Column('movies', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('friends', sa.String(), nullable=True),
    sa.Column('enemies', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monsters'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('fav_mon', sa.String(), nullable=True),
    sa.Column('fav_mov', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('buys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dolls', sa.String(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_buys_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buys'))
    )
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movies', sa.String(), nullable=True),
    sa.Column('episodes', sa.String(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_medias_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medias'))
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mon_name', sa.String(), nullable=True),
    sa.Column('origin_story', sa.String(), nullable=True),
    sa.Column('L_book', sa.String(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_stories_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stories')
    op.drop_table('medias')
    op.drop_table('buys')
    op.drop_table('users')
    op.drop_table('monsters')
    # ### end Alembic commands ###
