"""Create tables

Revision ID: b0a7f5833b39
Revises: 2224f925ec0c
Create Date: 2024-09-04 10:44:05.183999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a7f5833b39'
down_revision = '2224f925ec0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.drop_column('accessories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessories', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
