"""Create tables

Revision ID: b18606fd8634
Revises: e0b48674a2c2
Create Date: 2024-09-10 10:31:19.062468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18606fd8634'
down_revision = 'e0b48674a2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_story', sa.String(), nullable=True),
    sa.Column('L_book', sa.String(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_stories_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.drop_table('sbus')
    op.drop_table('smons')
    op.drop_table('smeds')
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_buys_monster_id_monsters'), 'monsters', ['monster_id'], ['id'])

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_medias_monster_id_monsters'), 'monsters', ['monster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_medias_monster_id_monsters'), type_='foreignkey')
        batch_op.drop_column('monster_id')

    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_buys_monster_id_monsters'), type_='foreignkey')
        batch_op.drop_column('monster_id')

    op.create_table('smeds',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('media_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], name='fk_smeds_media_id_medias'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_smeds_user_id_users')
    )
    op.create_table('smons',
    sa.Column('monster_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name='fk_smons_monster_id_monsters'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_smons_user_id_users')
    )
    op.create_table('sbus',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('buy_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['buy_id'], ['buys.id'], name='fk_sbus_buy_id_buys'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_sbus_user_id_users')
    )
    op.drop_table('stories')
    # ### end Alembic commands ###
