"""empty message

Revision ID: e0b48674a2c2
Revises: e1d44e0211cc
Create Date: 2024-09-06 10:05:56.520653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b48674a2c2'
down_revision = 'e1d44e0211cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buys_monster_id_monsters', type_='foreignkey')
        batch_op.drop_column('monster_id')

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_medias_monster_id_monsters', type_='foreignkey')
        batch_op.drop_column('monster_id')

    with op.batch_alter_table('sbus', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('buy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('save')
        batch_op.drop_column('id')

    with op.batch_alter_table('smeds', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('media_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('save')
        batch_op.drop_column('id')

    with op.batch_alter_table('smons', schema=None) as batch_op:
        batch_op.alter_column('monster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('monster_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('smeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('save', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('media_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sbus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('save', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('buy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monster_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_medias_monster_id_monsters', 'monsters', ['monster_id'], ['id'])

    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monster_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_buys_monster_id_monsters', 'monsters', ['monster_id'], ['id'])

    # ### end Alembic commands ###
