"""Create tables

Revision ID: e1d44e0211cc
Revises: 
Create Date: 2024-09-05 16:52:03.881861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d44e0211cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('parents', sa.String(), nullable=True),
    sa.Column('movies', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monsters'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('fav_mon', sa.String(), nullable=True),
    sa.Column('fav_mov', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('buys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dolls', sa.String(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_buys_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buys'))
    )
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movies', sa.String(), nullable=True),
    sa.Column('episodes', sa.String(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_medias_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medias'))
    )
    op.create_table('smons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_smons_monster_id_monsters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_smons_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smons'))
    )
    op.create_table('sbus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('save', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('buy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buy_id'], ['buys.id'], name=op.f('fk_sbus_buy_id_buys')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sbus_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sbus'))
    )
    op.create_table('smeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('save', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], name=op.f('fk_smeds_media_id_medias')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_smeds_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smeds'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smeds')
    op.drop_table('sbus')
    op.drop_table('smons')
    op.drop_table('medias')
    op.drop_table('buys')
    op.drop_table('users')
    op.drop_table('monsters')
    # ### end Alembic commands ###
